// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-Oc4jSJKhMfpVtwYyBb57tnumeqqvTyo',
    appId: '1:78745233828:web:3670824220c91ce231f931',
    messagingSenderId: '78745233828',
    projectId: 'yungyung-stock',
    authDomain: 'yungyung-stock.firebaseapp.com',
    storageBucket: 'yungyung-stock.appspot.com',
    measurementId: 'G-J4VZBTYKQ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmanbPSm8H01lHSk5pd4Kg_Qz97lNrQ2o',
    appId: '1:78745233828:android:363042b8894b5de131f931',
    messagingSenderId: '78745233828',
    projectId: 'yungyung-stock',
    storageBucket: 'yungyung-stock.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1jh9D2s64WY2R84SxgUyLArcUGZm0XQc',
    appId: '1:78745233828:ios:1afbc88459f2436331f931',
    messagingSenderId: '78745233828',
    projectId: 'yungyung-stock',
    storageBucket: 'yungyung-stock.appspot.com',
    iosBundleId: 'com.example.yungyungStockProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1jh9D2s64WY2R84SxgUyLArcUGZm0XQc',
    appId: '1:78745233828:ios:1afbc88459f2436331f931',
    messagingSenderId: '78745233828',
    projectId: 'yungyung-stock',
    storageBucket: 'yungyung-stock.appspot.com',
    iosBundleId: 'com.example.yungyungStockProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-Oc4jSJKhMfpVtwYyBb57tnumeqqvTyo',
    appId: '1:78745233828:web:ea64bc0126ab00d931f931',
    messagingSenderId: '78745233828',
    projectId: 'yungyung-stock',
    authDomain: 'yungyung-stock.firebaseapp.com',
    storageBucket: 'yungyung-stock.appspot.com',
    measurementId: 'G-542ELDSQN7',
  );
}
